'use strict'

const { spawnSync } = require('node:child_process')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { removeDirectory } = require('../harness/tempDir.cjs')

/** A workspace shaped for asserting behaviour rather than for measuring cost.
 *
 *  The perf fixture is eight files big enough to hurt; this one is three files and a
 *  git repository, each chosen so that every claim about them is checkable by eye:
 *
 *  - `edited.ts` is small enough that one viewport holds all three change regions at
 *    once, and every line carries its own number, so "this decoration is on line 12"
 *    is answered by reading the decorated element's text instead of by mapping DOM
 *    positions back to document offsets. It is also under FULL_VIEW_LIMIT, so the
 *    inline view's 「显示全文」 branch is reachable on it.
 *  - `oversized.txt` is deliberately over MAX_FILE_CONTENT_BYTES, which is the only
 *    way to reach the read-only surface: the server serves a bounded prefix and marks
 *    it truncated, and the viewer then mounts CodeMirror with `editable` false. The
 *    perf fixture is pinned *under* that cap for the opposite reason — a file you
 *    cannot type in cannot measure input latency — so neither fixture can stand in
 *    for the other.
 *  - `tracked.ts` is committed and then modified, which is the whole of what the Git
 *    panel needs: one file in a known state. `edited.ts` is deliberately *not* the
 *    modified one — its content has to keep matching the session diff's `+` lines or
 *    the editor checks lose their regions.
 *
 *  Written outside the repository, and removed again unless the run asks to keep it. */

const EDITED_FILE = 'edited.ts'
const OVERSIZED_FILE = 'oversized.txt'
const TRACKED_FILE = 'tracked.ts'
const EDITED_LINES = 400
/** Mirrors MAX_FILE_CONTENT_BYTES in apps/server/src/textFile.ts. */
const MAX_FILE_CONTENT_BYTES = 1024 * 1024
/** Mirrors FULL_VIEW_LIMIT in apps/web/src/editor/InlineDiffView.tsx: past this the
 *  「显示全文」 toggle is disabled, so `edited.ts` has to stay under it. */
const FULL_VIEW_LIMIT = 4000

/** The three changes, spaced so the app keeps them as three regions: `mergeRegions`
 *  folds anything that touches, and a deletion ends one line *before* its start, so
 *  neighbours two lines apart would become one bar. All three sit near the top so the
 *  first viewport shows every one of them without scrolling. */
const EDITS = Object.freeze([
  { line: 6, kind: 'add' },
  { line: 12, kind: 'modify' },
  { line: 18, kind: 'delete', removed: ['export const gone_1 = { id: 0 }', 'export const gone_2 = { id: 0 }'] }
])

/** A line well past the collapsed view's context windows (regions at 6/12/18 with
 *  three lines either side reach line 21) but still inside the expanded view's first
 *  window. Present only when 「显示全文」 is on, which is what makes it the test. */
const LINE_ONLY_VISIBLE_WHEN_EXPANDED = 30

function fixtureDir() {
  return path.join(os.tmpdir(), 'botcf-e2e-editor')
}

function rootName() {
  return path.basename(fixtureDir())
}

/** Every line is distinct and states its own number, so an assertion can name the
 *  line it expects and compare the text it got. */
function editedLine(number) {
  return `export const line_${String(number).padStart(4, '0')} = { id: ${number}, tag: 'e2e' }`
}

function editedContent() {
  const lines = ['// generated by e2e/fixture.cjs - safe to delete']
  for (let number = 2; number <= EDITED_LINES; number++) lines.push(editedLine(number))
  return lines.join('\n') + '\n'
}

/** Just over the cap: enough to be truncated, not so much that writing it is slow. */
function oversizedContent() {
  const line = 'x'.repeat(120) + '\n'
  const times = Math.ceil((MAX_FILE_CONTENT_BYTES + 64 * 1024) / line.length)
  return line.repeat(times)
}

function trackedContent(extra = false) {
  const lines = ['// committed by e2e/fixture.cjs', 'export const tracked = { id: 1 }']
  if (extra) lines.push('export const uncommitted = { id: 2 }')
  return lines.join('\n') + '\n'
}

/** Make the fixture a git repository with one committed file, then modify it.
 *
 *  Everything is local: `-c` for identity so the run never depends on the machine's
 *  git config, and `commit.gpgsign=false` so a developer who signs by default does
 *  not have the harness wait on a passphrase prompt that will never be answered.
 *
 *  Returns false when git is not usable. The run does not skip the Git checks on that
 *  — it fails them, with the reason. A check nobody ran is not a check that passed. */
function initRepository(dir) {
  const git = (...args) =>
    spawnSync('git', ['-C', dir, '-c', 'user.email=e2e@example.invalid', '-c', 'user.name=e2e', '-c', 'commit.gpgsign=false', ...args], {
      encoding: 'utf8',
      windowsHide: true
    })
  const init = git('init', '-q')
  if (init.error || init.status !== 0) return false
  fs.writeFileSync(path.join(dir, TRACKED_FILE), trackedContent(), 'utf8')
  for (const args of [['add', '.'], ['commit', '-q', '-m', 'e2e base']]) {
    const result = git(...args)
    if (result.error || result.status !== 0) return false
  }
  // The uncommitted change the Git panel is supposed to show.
  fs.writeFileSync(path.join(dir, TRACKED_FILE), trackedContent(true), 'utf8')
  return true
}

async function create() {
  const dir = fixtureDir()
  // Cleared first, and with the retrying remover rather than a bare rmSync. A
  // repository left behind by an earlier run would already have the modification
  // committed, so the Git panel would correctly show a clean tree and the checks
  // would fail for a reason that has nothing to do with the panel. And a bare
  // removal is what broke here twice: git writes `.git/objects` read-only, and a run
  // that was killed can leave the directory held for a moment after it exits.
  const cleared = await removeDirectory(dir)
  if (!cleared) throw new Error(`夹具目录删不掉,手动删除后重跑: ${dir}`)
  fs.mkdirSync(dir, { recursive: true })
  const edited = editedContent()
  const oversized = oversizedContent()
  // Assert the properties the specs depend on rather than trusting that an edit to
  // the templates above kept them — a fixture that quietly became editable would
  // turn the read-only checks green without testing anything.
  if (Buffer.byteLength(oversized, 'utf8') <= MAX_FILE_CONTENT_BYTES) {
    throw new Error('oversized fixture is not over the 1 MiB cap — it would be served editable')
  }
  if (Buffer.byteLength(edited, 'utf8') >= MAX_FILE_CONTENT_BYTES) {
    throw new Error('edited fixture crossed the 1 MiB cap — it would be served read-only')
  }
  if (EDITED_LINES >= FULL_VIEW_LIMIT) {
    throw new Error(`edited fixture is ${EDITED_LINES} lines, at or over FULL_VIEW_LIMIT ${FULL_VIEW_LIMIT} — 「显示全文」 would be disabled`)
  }
  fs.writeFileSync(path.join(dir, EDITED_FILE), edited, 'utf8')
  fs.writeFileSync(path.join(dir, OVERSIZED_FILE), oversized, 'utf8')
  const gitReady = initRepository(dir)
  return {
    dir,
    rootName: rootName(),
    files: [EDITED_FILE, OVERSIZED_FILE, TRACKED_FILE],
    editedLines: edited.split('\n'),
    editedPath: `${rootName()}/${EDITED_FILE}`,
    oversizedPath: `${rootName()}/${OVERSIZED_FILE}`,
    trackedPath: `${rootName()}/${TRACKED_FILE}`,
    trackedFile: TRACKED_FILE,
    gitReady
  }
}

function remove() {
  // Not a bare rmSync: this directory is a git repository, and git writes the files
  // under `.git/objects` read-only — the first version came back EPERM and took the
  // whole run's exit with it.
  return removeDirectory(fixtureDir())
}

module.exports = {
  create,
  remove,
  fixtureDir,
  rootName,
  EDITS,
  EDITED_FILE,
  OVERSIZED_FILE,
  TRACKED_FILE,
  EDITED_LINES,
  FULL_VIEW_LIMIT,
  LINE_ONLY_VISIBLE_WHEN_EXPANDED
}
