'use strict'

const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { buildSessionDiff, changedFile, spreadEdits } = require('../harness/sessionDiff.cjs')
const { removeDirectory } = require('../harness/tempDir.cjs')

/** The editing load from the 2026-08-24 report, as a directory a workspace can open.
 *
 *  Eight text files of 12,001 lines and just under 1 MB each — one per editor tab.
 *  Both numbers matter. 12,001 lines is what made a mounted viewer expensive (a line
 *  array plus a textarea the browser lays out line by line), and staying under
 *  MAX_FILE_CONTENT_BYTES (1 MiB) is what keeps every tab *editable*: over the cap the
 *  viewer serves a read-only preview, and a file you cannot type in cannot measure
 *  input latency.
 *
 *  Written outside the repository, and removed again unless the run asks to keep it —
 *  101k synthetic files left behind after the original measurement is a mess nobody
 *  wants to inherit. */

const FILE_COUNT = 8
const LINES = 12_001
/** Line payload; +1 for the newline gives 79 B/line → 948,079 B per file. */
const LINE_WIDTH = 78
const BYTES_PER_FILE = LINES * (LINE_WIDTH + 1)
const MAX_FILE_CONTENT_BYTES = 1024 * 1024
/** Mirrors FULL_VIEW_LIMIT in apps/web/src/editor/InlineDiffView.tsx — the line count
 *  past which 「显示全文」 is disabled. Pinned by apps/web/test/sessionDiffFixture.test.ts. */
const FULL_VIEW_LIMIT = 4_000

function fixtureDir() {
  return path.join(os.tmpdir(), 'botcf-perf-editor')
}

/** Root name the workspace will give this directory, i.e. the prefix of every
 *  qualified path the UI uses for these files. */
function rootName() {
  return path.basename(fixtureDir())
}

/** ASCII only, on purpose: the size assertion below compares bytes to characters. */
const HEADER = '// generated by perf/fixture.cjs - safe to delete'

function line(fileIndex, lineNumber) {
  const code = `export const s${fileIndex}_${String(lineNumber).padStart(5, '0')} = { id: ${lineNumber}, tag: 'perf' }`
  return pad(code)
}

function pad(text) {
  if (text.length > LINE_WIDTH) return text.slice(0, LINE_WIDTH)
  const padding = LINE_WIDTH - text.length
  // Pad to a fixed width so the file size is a property of the fixture, not of how
  // wide the identifiers happen to render.
  return padding > 3 ? `${text} //${'.'.repeat(padding - 3)}` : text + ' '.repeat(padding)
}

function fileContent(fileIndex) {
  const lines = new Array(LINES)
  lines[0] = pad(HEADER)
  for (let n = 1; n < LINES; n++) lines[n] = line(fileIndex, n)
  return lines.join('\n') + '\n'
}

function fileNames() {
  return Array.from({ length: FILE_COUNT }, (_, index) => `module-${index + 1}.ts`)
}

/** A ninth file, small enough that the inline view will expand it.
 *
 *  「显示全文」 refuses past FULL_VIEW_LIMIT (4,000 lines) and the eight files above are
 *  12,001, so the expanded branch was unreachable in this harness — the gate only ever
 *  measured the collapsed one. That branch is the interesting one: collapsed, the row
 *  count follows the *changes*; expanded, it follows the *file*, which is the shape
 *  that used to put thousands of rows of three elements each into the document.
 *
 *  Deliberately not one of the eight: those are the P2-004 reproduction and their
 *  count and size are the load. This one is carried alongside, opened only by the
 *  inline phase. */
const EXPANDABLE_FILE = 'expandable.ts'
const EXPANDABLE_LINES = 3_600
const EXPANDABLE_REGIONS = 120

function expandableContent() {
  const lines = new Array(EXPANDABLE_LINES)
  lines[0] = pad('// generated by perf/fixture.cjs - expandable inline fixture')
  for (let n = 1; n < EXPANDABLE_LINES; n++) lines[n] = line('x', n)
  return lines.join('\n') + '\n'
}

function expandablePath() {
  return `${rootName()}/${EXPANDABLE_FILE}`
}

/** Qualified workspace paths (`<rootName>/<file>`) — what the UI opens tabs with. */
function workspacePaths() {
  return fileNames().map((name) => `${rootName()}/${name}`)
}

function create() {
  const dir = fixtureDir()
  fs.mkdirSync(dir, { recursive: true })
  const names = fileNames()
  for (let index = 0; index < names.length; index++) {
    const file = path.join(dir, names[index])
    const content = fileContent(index)
    // The load is the measurement's independent variable: assert it rather than
    // trusting that a template edit kept it, or a later run compares to nothing.
    const bytes = Buffer.byteLength(content, 'utf8')
    if (bytes !== BYTES_PER_FILE) throw new Error(`fixture ${names[index]}: ${bytes} B, expected ${BYTES_PER_FILE} B`)
    if (bytes >= MAX_FILE_CONTENT_BYTES) throw new Error(`fixture ${names[index]} would be served read-only (${bytes} B)`)
    fs.writeFileSync(file, content, 'utf8')
  }
  // The expandable one is asserted from the other side: it has to stay *under*
  // FULL_VIEW_LIMIT or 「显示全文」 is disabled and the branch it exists for is
  // unreachable again, silently.
  if (EXPANDABLE_LINES >= FULL_VIEW_LIMIT) {
    throw new Error(`expandable fixture is ${EXPANDABLE_LINES} lines, at or over FULL_VIEW_LIMIT ${FULL_VIEW_LIMIT}`)
  }
  fs.writeFileSync(path.join(dir, EXPANDABLE_FILE), expandableContent(), 'utf8')
  return {
    dir,
    rootName: rootName(),
    files: names,
    expandable: EXPANDABLE_FILE,
    bytesPerFile: BYTES_PER_FILE,
    lines: LINES,
    expandableLines: EXPANDABLE_LINES
  }
}

function remove() {
  return removeDirectory(fixtureDir())
}

/** How many places the assistant "changed" in each file.
 *
 *  This is the inline view's load, and it is chosen the same way the file size was:
 *  by what it has to be able to make expensive. 「内联」 collapsed shows a
 *  DEFAULT_INLINE_CONTEXT window around every region plus one row per removed line
 *  and one per elided stretch, so 350 regions is roughly 3,150 rows of four elements
 *  each — some 12,000 elements if the view rendered all of them, against the ~160
 *  rows a viewport plus overscan holds. That ratio is what the gate checks.
 *
 *  It is also bounded from above by the app: the diff each file carries has to stay
 *  under DIFF_CAP or `changedFiles` would keep only its tail, and a truncated fixture
 *  is not the fixture the gate thinks it wrote. `buildSessionDiff` asserts that. */
const DIFF_REGIONS = 350

/** The files as one finished turn's `files_changed` summary.
 *
 *  Regenerates the content rather than reading it back, so the diff is built from the
 *  same bytes `create()` wrote — the additions have to match the file on disk exactly
 *  or `anchorRegions` drops them and the harness measures an empty view.
 *
 *  The expandable file is first so that the *last* entry — the one the turn brings to
 *  the front, and therefore the one the collapsed measurement lands on — is one of the
 *  eight big ones. The inline phase activates the expandable tab itself when it wants
 *  the expanded branch. */
function sessionDiffs() {
  const expandable = expandablePath()
  const expandableLines = expandableContent().split('\n')
  const changed = [
    changedFile(
      expandable,
      buildSessionDiff(expandable, expandableLines, spreadEdits(EXPANDABLE_LINES, EXPANDABLE_REGIONS))
    )
  ]
  for (const [index, name] of fileNames().entries()) {
    const lines = fileContent(index).split('\n')
    const displayPath = `${rootName()}/${name}`
    changed.push(changedFile(displayPath, buildSessionDiff(displayPath, lines, spreadEdits(LINES, DIFF_REGIONS))))
  }
  return changed
}

module.exports = {
  create,
  remove,
  fixtureDir,
  rootName,
  workspacePaths,
  expandablePath,
  sessionDiffs,
  FILE_COUNT,
  LINES,
  BYTES_PER_FILE,
  DIFF_REGIONS,
  EXPANDABLE_LINES,
  EXPANDABLE_REGIONS,
  FULL_VIEW_LIMIT
}
